networks:
  boz.net:
    driver: bridge

services:

  api:
    image: canals/php:latest
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: ./build/Dockerfile
    env_file: ./backend/app/config/token.env
    ports:
      - '54050:80'
    volumes:
      - ./backend/app:/var/php
    working_dir: /var/php
    networks:
      - boz.net
    depends_on:
      - postgres
    command: php -S 0.0.0.0:80 -t /var/php/public


  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    env_file: ./backend/app/config/postgres.env
    ports:
      - '54051:5432'
    networks:
      - boz.net
    volumes:
      - ./app/sql:/var/sql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - '54052:8080'
    networks:
      - boz.net
    command : php -S 0.0.0.0:8080 -t /var/www/html

  nodejs:
  image: node:latest
  restart: unless-stopped
  ports:
    - "54053:3000"
  volumes:
    - ./frontend:/app
  working_dir: /app
  networks:
    - boz.net
  depends_on:
    - api
  command: sh -c "npm install && npm run dev -- --host"